apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: cilium-oci
  values:
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    k8sServiceHost: kubernetes.default.svc
    k8sServicePort: 443
