apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lab-pool.yaml
  - lab-pool-adv.yaml
configMapGenerator:
  - name: metallb-config
    envs:
      - metallb-pool.properties
    options:
      disableNameSuffixHash: true
