apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - ../../base
namePrefix: dev-
configMapGenerator:
  - name: metallb-config
    behavior: replace
    envs:
      - metallb-pool.properties
    options:
      disableNameSuffixHash: true
replacements:
  - source:
      kind: ConfigMap
      name: metallb-config
      fieldPath: data.POOL_NAME
    targets:
      - select:
          kind: IPAddressPool
          name: example-pool
        fieldPaths:
          - metadata.name
  - source:
      kind: ConfigMap
      name: metallb-config
      fieldPath: data.IP_RANGE
    targets:
      - select:
          kind: IPAddressPool
          name: example-pool
        fieldPaths:
          - spec.addresses.0
  - source:
      kind: ConfigMap
      name: metallb-config
      fieldPath: data.POOL_ADV_NAME
    targets:
      - select:
          kind: L2Advertisement
          name: example-pool-adv
        fieldPaths:
          - metadata.name
  - source:
      kind: ConfigMap
      name: metallb-config
      fieldPath: data.POOL_NAME
    targets:
      - select:
          kind: L2Advertisement
          name: example-pool-adv
        fieldPaths:
          - spec.ipAddressPools.0
