---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  healthChecks:
  - kind: Deployment
    name: vote
    namespace: instavote
  - kind: Deployment
    name: result
    namespace: instavote
  - kind: Deployment
    name: worker
    namespace: instavote
  interval: 1m0s
  path: ./flux
  prune: true
  serviceAccountName: instavote
  targetNamespace: instavote
  timeout: 3m0s
  validation: client
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
