---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  interval: 1m0s
  secretRef: 
    name: instavote-deploy-git
  ref:
    branch: main
  url: https://github.com/minkzaw/instavote-deploy.git
