---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instavote
  namespace: instavote
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instavote
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['apps']
  resources: ['deployments']
  verbs: ['*']
- apiGroups: ['']
  resources: ['services']
  verbs: ['*']
- apiGroups: ['networking.k8s.io']
  resources: ['ingresses']
  verbs: ['*']
- apiGroups: ['helm.toolkit.fluxcd.io']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['source.toolkit.fluxcd.io']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['kustomize.toolkit.fluxcd.io']
  resources: ['*']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instavote
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: instavote
subjects:
- kind: ServiceAccount
  name: instavote
  namespace: instavote